Vagrant.configure("2") do |config|
  config.vm.box = "debian/stretch64"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
  end

  config.vm.network "private_network", ip: "192.168.37.37"
  config.vm.hostname = 'jenkins-satis'

  config.vm.synced_folder "salt", "/srv/salt", :nfs => true

  config.vm.provision :salt do |salt|
    salt.install_type = "stable"
    salt.masterless = true
    salt.minion_config = "salt/minion"
    salt.run_highstate = true
    salt.verbose = true
    salt.log_level = "info"
    salt.colorize = true
  end

  config.vm.post_up_message = "Head to http://192.168.37.37 to get started."
end
